# Generated by Django 3.2.5 on 2021-07-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
